### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by ferrine** [stepelu/ptstat#2]
Hello!
I found your repo in pytorch discourse. I'm a [pymc3](https://github.com/pymc-devs/pymc3) team member. Very happy that Bayes goes to pytorch too. We were planning to investigate if pytorch is suitable for bayesian reasoning. You can read our discussion [here](https://discourse.pymc.io/t/pymc4-pytorch/61/6). I'd like to leave some comments for future improvements

* Assertion errors can be hard to catch and if you have one, you can't figure out what type is it. I think some of assertions are not needed as they are checked at runtime without any supplementary code.

* Now I see all stuff in code. Hope in future it will be more organized. Distribution submodule with splitting to distribution types can be a good solution.

* Use pytest. I got used to unittest until tried pytest, now I have no way back to unittest, pytest is awesome

* Use docstrings instead of `# comment`. It can be helpfull for future users

* Remove NormalUnit and Uniform01, add defaults instead. Having lots of classes of the same distribution can be messy

**Comment by stepelu** [comment]
> I found your repo in pytorch discourse. I'm a pymc3 team member. Very happy that Bayes goes to pytorch too. We were planning to investigate if pytorch is suitable for bayesian reasoning. You can read our discussion here. I'd like to leave some comments for future improvements

Thanks for pointing this out. I am not familiar with Bayesian reasoning but I am with Bayesian inference.
From my cursory checking of PyMc3 it seems that it relies on a static graph approach, while PyTorch adopts a dynamic one, like Chainer.
Out of curiosity, is the approach for gradients (when needed) something among the lines of the [stochastic computational graphs](https://arxiv.org/abs/1506.05254) paper?
I'd like as much as possible to avoid re-inventing the wheel (also given I already developed a scientific library for another language), so I welcome integration / cooperation on this topic.

> Assertion errors can be hard to catch and if you have one, you can't figure out what type is it. I think some of assertions are not needed as they are checked at runtime without any supplementary code.

There are many assertions because by usage experience I discovered that it was very easy to make that kind of mistakes.
I was thinking of adding a flag to disable them, mainly for performance reasons.

> Now I see all stuff in code. Hope in future it will be more organized. Distribution submodule with splitting to distribution types can be a good solution.

It seemed overkill initially but it's a good point, I'll move to a more modular structure.

> Use pytest. I got used to unittest until tried pytest, now I have no way back to unittest, pytest is awesome

PyTorch relies on unittest only, so I'd like to follow the convention.

> Use docstrings instead of # comment. It can be helpfull for future users

Will do.

> Remove NormalUnit and Uniform01, add defaults instead. Having lots of classes of the same distribution can be messy

The thing is the constructor arguments are different: for instance NormalUnit takes as input a shape while NormalDiagonal the mean and standard deviation parameters, hence the number and type of arguments are different.
While your suggested solution is technically doable I am not completely convinced that it would be less confusing than the currently adopted one.
I'll ponder over it.

**Comment by stepelu** [comment]
I thought about it and will adopt your suggestion for reducing the number of distribution classes (last point).
